[package]
name = "custom-syscall"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program = "2.3.0"

[dev-dependencies]
mollusk-svm = "0.4.1"
solana-sdk = "2.3.1"

[lib]
crate-type = ["cdylib", "lib"]

